var newName;
var newLastName;
var newEmail;
var newPass;
var newPhone;
var newDocument;
var newDType;
var newCountry;

String loggedUserName = '';
String loggedUserLastName = '';
String loggedUserEmail = '';
int loggedUserPhone = 0;
var Invoices;

dynamic globalCountries = [
  {"id": "1", "Codigo": "AU", "Pais": "Australia"},
  {"id": "2", "Codigo": "CN", "Pais": "China"},
  {"id": "3", "Codigo": "JP", "Pais": "Japan"},
  {"id": "4", "Codigo": "TH", "Pais": "Thailand"},
  {"id": "5", "Codigo": "IN", "Pais": "India"},
  {"id": "6", "Codigo": "MY", "Pais": "Malaysia"},
  {"id": "7", "Codigo": "KR", "Pais": "Kore"},
  {"id": "8", "Codigo": "HK", "Pais": "Hong Kong"},
  {"id": "9", "Codigo": "TW", "Pais": "Taiwan"},
  {"id": "10", "Codigo": "PH", "Pais": "Philippines"},
  {"id": "11", "Codigo": "VN", "Pais": "Vietnam"},
  {"id": "12", "Codigo": "FR", "Pais": "France"},
  {"id": "13", "Codigo": "EU", "Pais": "Europe"},
  {"id": "14", "Codigo": "DE", "Pais": "Germany"},
  {"id": "15", "Codigo": "SE", "Pais": "Sweden"},
  {"id": "16", "Codigo": "IT", "Pais": "Italy"},
  {"id": "17", "Codigo": "GR", "Pais": "Greece"},
  {"id": "18", "Codigo": "ES", "Pais": "Spain"},
  {"id": "19", "Codigo": "AT", "Pais": "Austria"},
  {"id": "20", "Codigo": "GB", "Pais": "United Kingdom"},
  {"id": "21", "Codigo": "NL", "Pais": "Netherlands"},
  {"id": "22", "Codigo": "BE", "Pais": "Belgium"},
  {"id": "23", "Codigo": "CH", "Pais": "Switzerland"},
  {"id": "24", "Codigo": "AE", "Pais": "United Arab Emirates"},
  {"id": "25", "Codigo": "IL", "Pais": "Israel"},
  {"id": "26", "Codigo": "UA", "Pais": "Ukraine"},
  {"id": "27", "Codigo": "RU", "Pais": "Russian Federation"},
  {"id": "28", "Codigo": "KZ", "Pais": "Kazakhstan"},
  {"id": "29", "Codigo": "PT", "Pais": "Portugal"},
  {"id": "30", "Codigo": "SA", "Pais": "Saudi Arabia"},
  {"id": "31", "Codigo": "DK", "Pais": "Denmark"},
  {"id": "32", "Codigo": "IR", "Pais": "Ira"},
  {"id": "33", "Codigo": "NO", "Pais": "Norway"},
  {"id": "34", "Codigo": "US", "Pais": "United States"},
  {"id": "35", "Codigo": "MX", "Pais": "Mexico"},
  {"id": "36", "Codigo": "CA", "Pais": "Canada"},
  {"id": "37", "Codigo": "A1", "Pais": "Anonymous Proxy"},
  {"id": "38", "Codigo": "SY", "Pais": "Syrian Arab Republic"},
  {"id": "39", "Codigo": "CY", "Pais": "Cyprus"},
  {"id": "40", "Codigo": "CZ", "Pais": "Czech Republic"},
  {"id": "41", "Codigo": "IQ", "Pais": "Iraq"},
  {"id": "42", "Codigo": "TR", "Pais": "Turkey"},
  {"id": "43", "Codigo": "RO", "Pais": "Romania"},
  {"id": "44", "Codigo": "LB", "Pais": "Lebanon"},
  {"id": "45", "Codigo": "HU", "Pais": "Hungary"},
  {"id": "46", "Codigo": "GE", "Pais": "Georgia"},
  {"id": "47", "Codigo": "BR", "Pais": "Brazil"},
  {"id": "48", "Codigo": "AZ", "Pais": "Azerbaijan"},
  {"id": "49", "Codigo": "A2", "Pais": "Satellite Provider"},
  {"id": "50", "Codigo": "PS", "Pais": "Palestinian Territory"},
  {"id": "51", "Codigo": "LT", "Pais": "Lithuania"},
  {"id": "52", "Codigo": "OM", "Pais": "Oman"},
  {"id": "53", "Codigo": "SK", "Pais": "Slovakia"},
  {"id": "54", "Codigo": "RS", "Pais": "Serbia"},
  {"id": "55", "Codigo": "FI", "Pais": "Finland"},
  {"id": "56", "Codigo": "IS", "Pais": "Iceland"},
  {"id": "57", "Codigo": "BG", "Pais": "Bulgaria"},
  {"id": "58", "Codigo": "SI", "Pais": "Slovenia"},
  {"id": "59", "Codigo": "MD", "Pais": "Moldov"},
  {"id": "60", "Codigo": "MK", "Pais": "Macedonia"},
  {"id": "61", "Codigo": "LI", "Pais": "Liechtenstein"},
  {"id": "62", "Codigo": "JE", "Pais": "Jersey"},
  {"id": "63", "Codigo": "PL", "Pais": "Poland"},
  {"id": "64", "Codigo": "HR", "Pais": "Croatia"},
  {"id": "65", "Codigo": "BA", "Pais": "Bosnia and Herzegovina"},
  {"id": "66", "Codigo": "EE", "Pais": "Estonia"},
  {"id": "67", "Codigo": "LV", "Pais": "Latvia"},
  {"id": "68", "Codigo": "JO", "Pais": "Jordan"},
  {"id": "69", "Codigo": "KG", "Pais": "Kyrgyzstan"},
  {"id": "70", "Codigo": "RE", "Pais": "Reunion"},
  {"id": "71", "Codigo": "IE", "Pais": "Ireland"},
  {"id": "72", "Codigo": "LY", "Pais": "Libya"},
  {"id": "73", "Codigo": "LU", "Pais": "Luxembourg"},
  {"id": "74", "Codigo": "AM", "Pais": "Armenia"},
  {"id": "75", "Codigo": "VG", "Pais": "Virgin Island"},
  {"id": "76", "Codigo": "YE", "Pais": "Yemen"},
  {"id": "77", "Codigo": "BY", "Pais": "Belarus"},
  {"id": "78", "Codigo": "GI", "Pais": "Gibraltar"},
  {"id": "79", "Codigo": "MQ", "Pais": "Martinique"},
  {"id": "80", "Codigo": "PA", "Pais": "Panama"},
  {"id": "81", "Codigo": "DO", "Pais": "Dominican Republic"},
  {"id": "82", "Codigo": "GU", "Pais": "Guam"},
  {"id": "83", "Codigo": "PR", "Pais": "Puerto Rico"},
  {"id": "84", "Codigo": "VI", "Pais": "Virgin Island"},
  {"id": "85", "Codigo": "MN", "Pais": "Mongolia"},
  {"id": "86", "Codigo": "NZ", "Pais": "New Zealand"},
  {"id": "87", "Codigo": "SG", "Pais": "Singapore"},
  {"id": "88", "Codigo": "ID", "Pais": "Indonesia"},
  {"id": "89", "Codigo": "NP", "Pais": "Nepal"},
  {"id": "90", "Codigo": "PG", "Pais": "Papua New Guinea"},
  {"id": "91", "Codigo": "PK", "Pais": "Pakistan"},
  {"id": "92", "Codigo": "AP", "Pais": "Asia/Pacific Region"},
  {"id": "93", "Codigo": "BS", "Pais": "Bahamas"},
  {"id": "94", "Codigo": "LC", "Pais": "Saint Lucia"},
  {"id": "95", "Codigo": "AR", "Pais": "Argentina"},
  {"id": "96", "Codigo": "BD", "Pais": "Bangladesh"},
  {"id": "97", "Codigo": "TK", "Pais": "Tokelau"},
  {"id": "98", "Codigo": "KH", "Pais": "Cambodia"},
  {"id": "99", "Codigo": "MO", "Pais": "Macau"},
  {"id": "100", "Codigo": "MV", "Pais": "Maldives"},
  {"id": "101", "Codigo": "AF", "Pais": "Afghanistan"},
  {"id": "102", "Codigo": "NC", "Pais": "New Caledonia"},
  {"id": "103", "Codigo": "FJ", "Pais": "Fiji"},
  {"id": "104", "Codigo": "WF", "Pais": "Wallis and Futuna"},
  {"id": "105", "Codigo": "QA", "Pais": "Qatar"},
  {"id": "106", "Codigo": "AL", "Pais": "Albania"},
  {"id": "107", "Codigo": "BZ", "Pais": "Belize"},
  {"id": "108", "Codigo": "UZ", "Pais": "Uzbekistan"},
  {"id": "109", "Codigo": "KW", "Pais": "Kuwait"},
  {"id": "110", "Codigo": "ME", "Pais": "Montenegro"},
  {"id": "111", "Codigo": "PE", "Pais": "Peru"},
  {"id": "112", "Codigo": "BM", "Pais": "Bermuda"},
  {"id": "113", "Codigo": "CW", "Pais": "Curacao"},
  {"id": "114", "Codigo": "CO", "Pais": "Colombia"},
  {"id": "115", "Codigo": "VE", "Pais": "Venezuela"},
  {"id": "116", "Codigo": "CL", "Pais": "Chile"},
  {"id": "117", "Codigo": "EC", "Pais": "Ecuador"},
  {"id": "118", "Codigo": "ZA", "Pais": "South Africa"},
  {"id": "119", "Codigo": "IM", "Pais": "Isle of Man"},
  {"id": "120", "Codigo": "BO", "Pais": "Bolivia"},
  {"id": "121", "Codigo": "GG", "Pais": "Guernsey"},
  {"id": "122", "Codigo": "MT", "Pais": "Malta"},
  {"id": "123", "Codigo": "TJ", "Pais": "Tajikistan"},
  {"id": "124", "Codigo": "SC", "Pais": "Seychelles"},
  {"id": "125", "Codigo": "BH", "Pais": "Bahrain"},
  {"id": "126", "Codigo": "EG", "Pais": "Egypt"},
  {"id": "127", "Codigo": "ZW", "Pais": "Zimbabwe"},
  {"id": "128", "Codigo": "LR", "Pais": "Liberia"},
  {"id": "129", "Codigo": "KE", "Pais": "Kenya"},
  {"id": "130", "Codigo": "GH", "Pais": "Ghana"},
  {"id": "131", "Codigo": "NG", "Pais": "Nigeria"},
  {"id": "132", "Codigo": "TZ", "Pais": "Tanzani"},
  {"id": "133", "Codigo": "ZM", "Pais": "Zambia"},
  {"id": "134", "Codigo": "MG", "Pais": "Madagascar"},
  {"id": "135", "Codigo": "AO", "Pais": "Angola"},
  {"id": "136", "Codigo": "NA", "Pais": "Namibia"},
  {"id": "137", "Codigo": "CI", "Pais": "Cote D'Ivoire"},
  {"id": "138", "Codigo": "SD", "Pais": "Sudan"},
  {"id": "139", "Codigo": "CM", "Pais": "Cameroon"},
  {"id": "140", "Codigo": "MW", "Pais": "Malawi"},
  {"id": "141", "Codigo": "GA", "Pais": "Gabon"},
  {"id": "142", "Codigo": "ML", "Pais": "Mali"},
  {"id": "143", "Codigo": "BJ", "Pais": "Benin"},
  {"id": "144", "Codigo": "TD", "Pais": "Chad"},
  {"id": "145", "Codigo": "BW", "Pais": "Botswana"},
  {"id": "146", "Codigo": "CV", "Pais": "Cape Verde"},
  {"id": "147", "Codigo": "RW", "Pais": "Rwanda"},
  {"id": "148", "Codigo": "CG", "Pais": "Congo"},
  {"id": "149", "Codigo": "UG", "Pais": "Uganda"},
  {"id": "150", "Codigo": "MZ", "Pais": "Mozambique"},
  {"id": "151", "Codigo": "GM", "Pais": "Gambia"},
  {"id": "152", "Codigo": "LS", "Pais": "Lesotho"},
  {"id": "153", "Codigo": "MU", "Pais": "Mauritius"},
  {"id": "154", "Codigo": "MA", "Pais": "Morocco"},
  {"id": "155", "Codigo": "DZ", "Pais": "Algeria"},
  {"id": "156", "Codigo": "GN", "Pais": "Guinea"},
  {"id": "157", "Codigo": "CD", "Pais": "Cong"},
  {"id": "158", "Codigo": "SZ", "Pais": "Swaziland"},
  {"id": "159", "Codigo": "BF", "Pais": "Burkina Faso"},
  {"id": "160", "Codigo": "SL", "Pais": "Sierra Leone"},
  {"id": "161", "Codigo": "SO", "Pais": "Somalia"},
  {"id": "162", "Codigo": "NE", "Pais": "Niger"},
  {"id": "163", "Codigo": "CF", "Pais": "Central African Republic"},
  {"id": "164", "Codigo": "TG", "Pais": "Togo"},
  {"id": "165", "Codigo": "BI", "Pais": "Burundi"},
  {"id": "166", "Codigo": "GQ", "Pais": "Equatorial Guinea"},
  {"id": "167", "Codigo": "SS", "Pais": "South Sudan"},
  {"id": "168", "Codigo": "SN", "Pais": "Senegal"},
  {"id": "169", "Codigo": "MR", "Pais": "Mauritania"},
  {"id": "170", "Codigo": "DJ", "Pais": "Djibouti"},
  {"id": "171", "Codigo": "KM", "Pais": "Comoros"},
  {"id": "172", "Codigo": "IO", "Pais": "British Indian Ocean Territory"},
  {"id": "173", "Codigo": "TN", "Pais": "Tunisia"},
  {"id": "174", "Codigo": "GL", "Pais": "Greenland"},
  {"id": "175", "Codigo": "VA", "Pais": "Holy See (Vatican City State)"},
  {"id": "176", "Codigo": "CR", "Pais": "Costa Rica"},
  {"id": "177", "Codigo": "KY", "Pais": "Cayman Islands"},
  {"id": "178", "Codigo": "JM", "Pais": "Jamaica"},
  {"id": "179", "Codigo": "GT", "Pais": "Guatemala"},
  {"id": "180", "Codigo": "MH", "Pais": "Marshall Islands"},
  {"id": "181", "Codigo": "AQ", "Pais": "Antarctica"},
  {"id": "182", "Codigo": "BB", "Pais": "Barbados"},
  {"id": "183", "Codigo": "AW", "Pais": "Aruba"},
  {"id": "184", "Codigo": "MC", "Pais": "Monaco"},
  {"id": "185", "Codigo": "AI", "Pais": "Anguilla"},
  {"id": "186", "Codigo": "KN", "Pais": "Saint Kitts and Nevis"},
  {"id": "187", "Codigo": "GD", "Pais": "Grenada"},
  {"id": "188", "Codigo": "PY", "Pais": "Paraguay"},
  {"id": "189", "Codigo": "MS", "Pais": "Montserrat"},
  {"id": "190", "Codigo": "TC", "Pais": "Turks and Caicos Islands"},
  {"id": "191", "Codigo": "AG", "Pais": "Antigua and Barbuda"},
  {"id": "192", "Codigo": "TV", "Pais": "Tuvalu"},
  {"id": "193", "Codigo": "PF", "Pais": "French Polynesia"},
  {"id": "194", "Codigo": "SB", "Pais": "Solomon Islands"},
  {"id": "195", "Codigo": "VU", "Pais": "Vanuatu"},
  {"id": "196", "Codigo": "ER", "Pais": "Eritrea"},
  {"id": "197", "Codigo": "TT", "Pais": "Trinidad and Tobago"},
  {"id": "198", "Codigo": "AD", "Pais": "Andorra"},
  {"id": "199", "Codigo": "HT", "Pais": "Haiti"},
  {"id": "200", "Codigo": "SH", "Pais": "Saint Helena"},
  {"id": "201", "Codigo": "FM", "Pais": "Micronesi"},
  {"id": "202", "Codigo": "SV", "Pais": "El Salvador"},
  {"id": "203", "Codigo": "HN", "Pais": "Honduras"},
  {"id": "204", "Codigo": "UY", "Pais": "Uruguay"},
  {"id": "205", "Codigo": "LK", "Pais": "Sri Lanka"},
  {"id": "206", "Codigo": "EH", "Pais": "Western Sahara"},
  {"id": "207", "Codigo": "CX", "Pais": "Christmas Island"},
  {"id": "208", "Codigo": "WS", "Pais": "Samoa"},
  {"id": "209", "Codigo": "SR", "Pais": "Suriname"},
  {"id": "210", "Codigo": "CK", "Pais": "Cook Islands"},
  {"id": "211", "Codigo": "KI", "Pais": "Kiribati"},
  {"id": "212", "Codigo": "NU", "Pais": "Niue"},
  {"id": "213", "Codigo": "TO", "Pais": "Tonga"},
  {"id": "214", "Codigo": "TF", "Pais": "French Southern Territories"},
  {"id": "215", "Codigo": "YT", "Pais": "Mayotte"},
  {"id": "216", "Codigo": "NF", "Pais": "Norfolk Island"},
  {"id": "217", "Codigo": "BN", "Pais": "Brunei Darussalam"},
  {"id": "218", "Codigo": "TM", "Pais": "Turkmenistan"},
  {"id": "219", "Codigo": "PN", "Pais": "Pitcairn Islands"},
  {"id": "220", "Codigo": "SM", "Pais": "San Marino"},
  {"id": "221", "Codigo": "AX", "Pais": "Aland Islands"},
  {"id": "222", "Codigo": "FO", "Pais": "Faroe Islands"},
  {"id": "223", "Codigo": "SJ", "Pais": "Svalbard and Jan Mayen"},
  {"id": "224", "Codigo": "CC", "Pais": "Cocos (Keeling) Islands"},
  {"id": "225", "Codigo": "NR", "Pais": "Nauru"},
];
